### ISSUE TITLE
Language Feature Checklist

### ISSUE THREAD

**Issue by Idyllei** [Idyllei/charon-lang#1]
The following features must be met to be considered Charon v1.0:

- [ ] Type creation
   - [ ]  Refined types
  - [ ] New types
  - [ ] Type inheritance
- [ ] Code separation
- [ ] Code reuse
  - [ ] First-class functions
  - [ ] Modules
- [ ] Metadata
  - [ ] Documentation
  - [ ] Compiler hints
  - [ ] Annotations a la Python/Java
- [ ] Minimal standard library
  - [ ] Numeric typeclasses
    - [ ] Integer
    - [ ] Rational
    - [ ] Decimal
    - [ ] Complex
    - [ ] Quaternion
    - [ ] Octonian
  - [ ] String modification
    - [ ] Interpolation
  - [ ] Collections
- [ ] Smart Implicits a la Scala
  - [ ] Clean syntax
- [ ] Concurrent programming capabilities
